@startuml
'https://plantuml.com/sequence-diagram

autonumber

客户端 -> 提议者: 客户端请求
group 准备阶段
提议者 -> 接受者: 准备请求 [提案号, ]
接受者 -> 提议者: 准备响应 [已接受提案号]
end
group 接受阶段
提议者 -> 接受者: 接受请求 [提案号, 值]
提议者 <-> 学习者: 接受响应
end
提议者 -> 客户端: 服务器响应
@enduml
